main/urls.py
from django.conf.urls import url

from main.views import SongBookView


urlpatterns = [
    url(r'^$', SongBookView.as_view(), name='home'),
]

songbook/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace='main')),
]

main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.forms import formset_factory


class TitleForm(forms.Form):
    title = forms.CharField(label='Songbook General Tite', required=False)


class SongBookForm(forms.Form):
    song = forms.CharField(label='Song', widget=forms.Textarea)


SongBookFormSet = formset_factory(SongBookForm, extra=5)

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import RequestContext
from django.template.loader import get_template
from django.views.generic import FormView

from weasyprint import HTML

from main.forms import SongBookForm, SongBookFormSet


from django.forms import formset_factory


class SongBookView(FormView):
    """Show songbook form."""

    template_name = 'main/songbook_form.html'
    form_class = SongBookFormSet
    success_url = '/'

    def form_valid(self, form):
        html_template = get_template('main/pdf.html')
        context = {}
        context['title'] = form.data['title'] \
            if 'title' in form.data else None
        context['songs'] = [
            single_form.cleaned_data['song'] for single_form in form
            if 'song' in single_form.cleaned_data]
        rendered_html = html_template.render(
            RequestContext(self.request, context)).encode(encoding="UTF-8")
        pdf_file = HTML(string=rendered_html).write_pdf()
        http_response = HttpResponse(pdf_file, content_type='application/pdf')
        filename = 'songbook.pdf'
        http_response['Content-Disposition'] = 'inline; filename="{}"'.format(
            filename)
        return http_response

main/templates/main/pdf.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
    <body>
		{% if title %}
			<h1 style="text-align: center;">{{ title }}</h1>
			<div style="page-break-before:always">&nbsp;</div>
		{% endif %}
		{% for song in songs %}
			<pre>{{ song|safe }}</pre>
			<div style="page-break-before:always">&nbsp;</div> 
		{% endfor %}
	</body>
</html>

main/templates/main/songbook_form.html
{% extends "songbook/base.html" %}

{% block content %}
	<h1>Create your SongBook:</h1>

            <form action="{% url 'main:home' %}" class="form" method="post">
	            {% csrf_token %}
	            	<h3>Songbook General Tite</h3>
	            	<input id="general_title" name="title" type="text">

	            {% for single_form in form %}
	            	{% for field in single_form %}
	            		<h3>{{ field.label }}</h3>
	            		<div class="field">{{ field }}</div>
	            	{% endfor %}
	            {% endfor %}
	            {{ form.management_form }}
	            <!-- <button type="submit" class="button" name="add">Add another song</button> -->
	            <button type="submit" class="button" name="pdf">Generate PDF</button>
	        </form>

{% endblock content %}

songbook/templates/songbook/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>SongBook</title>
        <link rel="stylesheet" href="{% static 'songbook/css/main.css' %}">
        {% block header %}
        {% endblock header %}
    </head>
    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>